quoteapp/urls.py
from django.urls import path
from quoteapp import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('create_author/', views.create_author, name='create_author'),
    path('create_tag/', views.create_tag, name='create_tag'),
    path('create_quote/', views.create_quote, name='create_quote'),
    path('authors/', views.authors_list, name='authors_list'),
    path('quotes/', views.quotes_list, name='quotes_list'),
    path('author/<int:pk>/', views.author_detail, name='author_detail'),
    path('tag/<int:pk>/', views.tag_detail, name='tag_detail'),
    path('quote/<int:pk>/', views.quote_detail, name='quote_detail'),
    path('tag/<int:pk>/', views.tag_detail, name='tag_detail'),
    path('quote/<int:pk>/', views.quote_detail, name='quote_detail'),
    path('authors_list/', views.authors_list, name='authors_list'),
    path('tags_list/', views.tags_list, name='tags_list'),
    path('quotes_list/', views.quotes_list, name='quotes_list'),
]

quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

quoteapp/models.py
from django.contrib.auth.models import User
from django.db import models

class Author(models.Model):
    fullname = models.CharField(max_length=100, null=False)
    born_date = models.CharField(max_length=50, null=False)
    born_location = models.CharField(max_length=100, null=False)
    description = models.TextField()

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=25, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name', 'user'], name='tag of username')
        ]

    def __str__(self):
        return f"{self.name}"


class Quote(models.Model):
    quote = models.TextField(null=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f"{self.quote}"

class MyModel(models.Model):
    data = models.JSONField(null=True)

    def __str__(self):
        return str(self.id)

users/models.py
from django.db import models

# Create your models here.

quoteapp/forms.py
from django import forms
from quoteapp.models import Tag, Quote, Author

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

quoteapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from quoteapp.forms import AuthorForm, QuoteForm, TagForm
from  quoteapp.models import Author, Quote, Tag
# Create your views here.
def main(request):
    return render(request, 'quoteapp/index.html')

@login_required
def create_author(request):
    if request.method == 'POST':
        author_form = AuthorForm(request.POST)
        if author_form.is_valid():
            author = author_form.save()
            return redirect('quoteapp:authors_list')
    else:
        author_form = AuthorForm()

    return render(request, 'quoteapp/create_author.html', {'author_form': author_form})

@login_required
def create_tag(request):
    if request.method == 'POST':
        tag_form = TagForm(request.POST)
        if tag_form.is_valid():
            tag = tag_form.save(commit=False)
            tag.user = request.user
            tag.save()
            return redirect('quoteapp:tags_list')
    else:
        tag_form = TagForm()

    return render(request, 'quoteapp/create_tag.html', {'tag_form': tag_form})

@login_required
def create_quote(request):
    if request.method == 'POST':
        quote_form = QuoteForm(request.POST)
        if quote_form.is_valid():
            quote = quote_form.save()
            return redirect('quoteapp:quotes_list')
    else:
        quote_form = QuoteForm()

    return render(request, 'quoteapp/create_quote.html', {'quote_form': quote_form})


def authors_list(request):
    authors = Author.objects.all()
    return render(request, 'quoteapp/authors_list.html', {'authors': authors})

def quotes_list(request):
    quotes = Quote.objects.all()
    return render(request, 'quoteapp/quotes_list.html', {'quotes': quotes})

def tags_list(request):
    tags = Tag.objects.all()
    return render(request, 'quoteapp/tags_list.html', {'tags': tags})

def author_detail(request, pk):
    author = get_object_or_404(Author, pk=pk)
    return render(request, 'quoteapp/author_detail.html', {'author': author})

def tag_detail(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    return render(request, 'quoteapp/tag_detail.html', {'tag': tag})

def quote_detail(request, pk):
    quote = get_object_or_404(Quote, pk=pk)
    return render(request, 'quoteapp/quote_detail.html', {'quote': quote})

users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from users.forms import RegisterForm, LoginForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quoteapp:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})

def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quoteapp:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quoteapp:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})

@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quoteapp:main')

quoteapp/templates/quoteapp/author_detail.html
{% extends "quoteapp/base.html" %}

{% block content %}
  <h1>Author Detail</h1>
  <p><strong>Author's Full Name:</strong> {{ author.fullname }}</p>
  <p><strong>Date of Birth:</strong> {{ author.born_date }}</p>
  <p><strong>Place of Birth:</strong> {{ author.born_location }}</p>
  <p><strong>Description:</strong> {{ author.description }}</p>


  <a href="{% url 'quoteapp:authors_list' %}">Back to Authors List</a>
{% endblock %}

quoteapp/templates/quoteapp/authors_list.html
{% extends "quoteapp/base.html" %}

{% block content %}
<h1>Authors</h1>
<ul>
    {% for author in authors %}
    <li><a href="{% url 'quoteapp:author_detail' pk=author.pk %}">{{ author.fullname }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes for all occasions</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="{% url 'quoteapp:main' %}" role="button">Go back to the main page</a></li>
        </ul>
        {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url 'quoteapp:create_quote' %}" role="button">Add Quote</a></li>
            <li><a href="{% url 'quoteapp:create_tag' %}" role="button">Add Tag</a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        {% endif %}
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

quoteapp/templates/quoteapp/create_author.html
{% extends "quoteapp/base.html" %}

{% block content %}
{% if user.is_authenticated %}
    <form method="POST" action="{% url 'quoteapp:create_author' %}">
        {% csrf_token %}
        <div style="padding: 10px">
            <label> Author's Full Name:
                {{ author_form.fullname }}
            </label>
            <span>{{ author_form.errors.fullname }}</span>
        </div>
        <div style="padding: 10px">
            <label> Date of Birth:
                {{ author_form.born_date }}
            </label>
            <span>{{ author_form.errors.born_date }}</span>
        </div>
        <div style="padding: 10px">
            <label> Place of Birth:
                {{ author_form.born_location }}
            </label>
            <span>{{ author_form.errors.born_location }}</span>
        </div>
        <div style="padding: 10px">
            <label> Description:
                {{ author_form.description }}
            </label>
            <span>{{ author_form.errors.description }}</span>
        </div>
        <div class="grid">
            <button type="submit">Submit</button>
            <button type="reset" class="secondary">Reset</button>
        </div>
    </form>
{% else %}
    <p>You must be <a href="{% url 'users:login' %}">logged in</a> to create an author.</p>
{% endif %}
{% endblock %}

quoteapp/templates/quoteapp/create_quote.html
{% extends "quoteapp/base.html" %}

{% block content %}
{% if user.is_authenticated %}
    <form method="POST" action="{% url 'quoteapp:create_quote' %}">
        {% csrf_token %}
        <div style="padding: 10px">
            <label> Quote author:
                {{ quote_form.author }}
            </label>
            <span>{{ quote_form.errors.author }}</span>
        </div>
        <div style="padding: 10px">
            <label> Quote:
                {{ quote_form.quote }}
            </label>
            <span>{{ quote_form.errors.quote }}</span>
        </div>
        <div style="padding: 10px">
            <label> Select tags:
                {{ quote_form.tags }}
            </label>
            <span>{{ quote_form.errors.tags }}</span>
        </div>
        <div class="grid">
            <button type="submit">Submit</button>
            <button type="reset" class="secondary">Reset</button>
        </div>
    </form>
{% else %}
    <p>You must be <a href="{% url 'users:login' %}">logged in</a> to create a quote.</p>
{% endif %}
{% endblock %}

quoteapp/templates/quoteapp/create_tag.html
{% extends "quoteapp/base.html" %}

{% block content %}
{% if user.is_authenticated %}
    <form method="POST" action="{% url 'quoteapp:create_tag' %}">
        {% csrf_token %}
        <div style="padding: 10px">
            <label> Tag name:
                {{ tag_form.name }}
            </label>
            <span>{{ tag_form.errors.name }}</span>
        </div>
        <div class="grid">
            <button type="submit">Submit</button>
            <button type="reset" class="secondary">Reset</button>
        </div>
    </form>
{% else %}
    <p>You must be <a href="{% url 'users:login' %}">logged in</a> to create a tag.</p>
{% endif %}
{% endblock %}

quoteapp/templates/quoteapp/detail.html
{% extends "quoteapp/base.html" %}
{% block content %}
<h1>{{ quote.author.fullname }}</h1>
<p>Description: <b>{{ quote.author.description }}</b></p>
<p>Quote: {{ quote.quote }}</p>
<p>Tags: <small>{{ quote.tags.all|join:', ' }}</small></p>
{% endblock %}

quoteapp/templates/quoteapp/index.html
{% extends "quoteapp/base.html" %}

{% block content %}
<h1>Welcome to Quotes App</h1>
<p>Select an option:</p>
<ul>
    <li><a href="{% url 'quoteapp:create_quote' %}">Add a Quote</a></li>
    <li><a href="{% url 'quoteapp:create_tag' %}">Add a Tag</a></li>
    <li><a href="{% url 'quoteapp:authors_list' %}">View Authors</a></li> <!-- Додано -->
    <li><a href="{% url 'quoteapp:quotes_list' %}">View Quotes</a></li> <!-- Додано -->
</ul>

{% for quote in quotes %}
    <h1>{{ quote.quote }}</h1>
    <p>Author: {{ quote.author.fullname }}</p>
    <p>Tags: {% for tag in quote.tags.all %}{{ tag.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
    <a href="{% url 'quoteapp:detail' quoteid=quote.id %}">Read more</a>
    <a href="{% url 'quoteapp:delete_quote' quoteid=quote.id %}">Delete</a>
{% endfor %}
{% endblock %}

quoteapp/templates/quoteapp/quote_detail.html
{% extends "quoteapp/base.html" %}

{% block content %}
  <h1>Quote Detail</h1>
  <p><strong>Text:</strong> {{ quote.text }}</p>
  <p><strong>Author:</strong> <a href="{% url 'quoteapp:author_detail' quote.author.pk %}">{{ quote.author.fullname }}</a></p>
  <p><strong>Tags:</strong></p>
  <ul>
    {% for tag in quote.tags.all %}
      <li><a href="{% url 'quoteapp:tag_detail' tag.pk %}">{{ tag.name }}</a></li>
    {% endfor %}
  </ul>
  <a href="{% url 'quoteapp:quotes_list' %}">Back to Quotes List</a>
{% endblock %}

quoteapp/templates/quoteapp/quotes_list.html
{% extends "quoteapp/base.html" %}

{% block content %}
<h1>Quotes</h1>
<ul>
    {% for quote in quotes %}
    <li><a href="{% url 'quoteapp:quote_detail' pk=quote.pk %}">{{ quote.quote }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

quoteapp/templates/quoteapp/tag_detail.html
{% extends "quoteapp/base.html" %}

{% block content %}
  <h1>Tag Detail</h1>
  <p><strong>Tag Name:</strong> {{ tag.name }}</p>
  <p><strong>Quotes with this tag:</strong></p>
  <ul>
    {% for quote in tag.quotes.all %}
      <li><a href="{% url 'quoteapp:quote_detail' quote.pk %}">{{ quote.text }}</a></li>
    {% endfor %}
  </ul>
  <a href="{% url 'quoteapp:tags_list' %}">Back to Tags List</a>
{% endblock %}

quoteapp/templates/quoteapp/tags_list.html
{% extends "quoteapp/base.html" %}

{% block content %}
  <h2>Список тегів</h2>
  <ul>
    {% for tag in tags %}
      <li><a href="{% url 'tag_detail' tag.pk %}">{{ tag.name }}</a></li>
    {% empty %}
      <li>На даний момент немає жодного тегу.</li>
    {% endfor %}
  </ul>
  <a href="{% url 'create_tag' %}">Додати тег</a>
  <br><br>
  <a href="{% url 'main' %}">На головну</a>
{% endblock %}

users/templates/users/login.html
{% extends "quoteapp/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

users/templates/users/signup.html
{% extends "quoteapp/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}